// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Title string `json:"title"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type ListResponse struct {
	Todos []Todo `json:"todos"`
}

type Todo struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
	CreatedAt string `json:"created_at"`
	Page     int `json:"Page"`
	PageSize int `json:"PageSize"`
}

type UpdateRequest struct {
	Id        int64 `json:"id"`
	Completed bool  `json:"completed"`
}
