// Code generated by goctl. DO NOT EDIT.
package types

type BaseResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	UserInfo UserInfo `json:"userInfo"`
	Token    string   `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Password string `json:"password" validate:"required,min=6,max=30"`
	Email    string `json:"email,optional" validate:"email"`
	Phone    string `json:"phone,optional" validate:"len=11"`
}

type UpdateUserReq struct {
	Id    int64  `path:"id"`
	Email string `json:"email,optional" validate:"email"`
	Phone string `json:"phone,optional" validate:"len=11"`
}

type UserIdReq struct {
	Id int64 `path:"id"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email,optional"` // 可选字段
	Phone    string `json:"phone,optional"`
	CreateAt string `json:"createAt,optional"`
	UpdateAt string `json:"updateAt,optional"`
}

type UserListReq struct {
	Page     int    `form:"page,default=1" validate:"min=1"`              // 当前页码
	PageSize int    `form:"pageSize,default=10" validate:"min=1,max=100"` // 每页数量
	Keyword  string `form:"keyword,optional"`                             // 搜索关键词
}

type UserListResp struct {
	CurrentPage int        `json:"currentPage"`
	PageSize    int        `json:"pageSize"`
	Total       int64      `json:"total"`
	List        []UserInfo `json:"list"`
}
